In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('cruise_ship_info.csv')

In [3]:
df.head()

Ship_name Cruise_line  Age  TonnageGTx1000  passengersx100  lengthx100ft  \
0      Journey     Azamara    6          30.277            6.94          5.94   
1        Quest     Azamara    6          30.277            6.94          5.94   
2  Celebration    Carnival   26          47.262           14.86          7.22   
3     Conquest    Carnival   11         110.000           29.74          9.53   
4      Destiny    Carnival   17         101.353           26.42          8.92   

   cabinsx100  spaceratio  crewx100  
0        3.55       42.64      3.55  
1        3.55       42.64      3.55  
2        7.43       31.80      6.70  
3       14.88       36.99     19.10  
4       13.21       38.36     10.00

In [4]:
df.shape

(158, 9)

In [5]:
df.isnull().sum() 

Ship_name         0
Cruise_line       0
Age               0
TonnageGTx1000    0
passengersx100    0
lengthx100ft      0
cabinsx100        0
spaceratio        0
crewx100          0
dtype: int64

In [6]:
x = df.drop(["Ship_name","Cruise_line"],axis = 1)

In [7]:
x

Age  TonnageGTx1000  passengersx100  lengthx100ft  cabinsx100  \
0      6          30.277            6.94          5.94        3.55   
1      6          30.277            6.94          5.94        3.55   
2     26          47.262           14.86          7.22        7.43   
3     11         110.000           29.74          9.53       14.88   
4     17         101.353           26.42          8.92       13.21   
..   ...             ...             ...           ...         ...   
153   22           3.341            0.66          2.79        0.33   
154   14          76.800           19.60          8.79        9.67   
155   25           5.350            1.58          4.40        0.74   
156   27           5.350            1.67          4.40        0.74   
157   23          14.745            3.08          6.17        1.56   

     spaceratio  crewx100  
0         42.64      3.55  
1         42.64      3.55  
2         31.80      6.70  
3         36.99     19.10  
4         38.36     10.00  
..          ...       ...  
153       50.62      0.59  
154       39.18     12.00  
155       33.86      0.88  
156       32.04      0.88  
157       47.87      1.80  

[158 rows x 7 columns]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
x1=scaler.fit_transform(x)

In [9]:
x1=pd.DataFrame(x1)
x1

0         1         2         3         4         5         6
0   -1.276402 -1.104984 -1.193956 -1.225331 -1.184588  0.318057 -1.215267
1   -1.276402 -1.104984 -1.193956 -1.225331 -1.184588  0.318057 -1.215267
2    1.358105 -0.647310 -0.372926 -0.509363 -0.314095 -0.940676 -0.313304
3   -0.617775  1.043215  1.169614  0.782736  1.357341 -0.338017  3.237281
4    0.172577  0.810215  0.825445  0.441533  0.982670 -0.178934  0.631610
..        ...       ...       ...       ...       ...       ...       ...
153  0.831204 -1.830796 -1.844975 -2.987284 -1.907008  1.244688 -2.062826
154 -0.222599  0.148615  0.118448  0.368817  0.188457 -0.083716  1.204285
155  1.226380 -1.776662 -1.749603 -2.086730 -1.815023 -0.701471 -1.979788
156  1.489831 -1.776662 -1.740273 -2.086730 -1.815023 -0.912808 -1.979788
157  0.962929 -1.523507 -1.594104 -1.096680 -1.631052  0.925360 -1.716358

[158 rows x 7 columns]

In [10]:
x1.describe()

0             1             2             3             4  \
count  1.580000e+02  1.580000e+02  1.580000e+02  1.580000e+02  1.580000e+02   
mean   9.556350e-17 -2.360981e-16  2.023698e-16  8.094791e-16 -1.124276e-17   
std    1.003180e+00  1.003180e+00  1.003180e+00  1.003180e+00  1.003180e+00   
min   -1.539853e+00 -1.858066e+00 -1.844975e+00 -2.987284e+00 -1.907008e+00   
25%   -7.495006e-01 -6.809653e-01 -6.139483e-01 -5.764847e-01 -6.051945e-01   
50%   -2.225992e-01  1.655359e-02  1.080810e-01  2.373698e-01  1.660218e-01   
75%    5.677530e-01  5.251151e-01  6.621724e-01  7.715492e-01  4.610472e-01   
max    4.256063e+00  4.007253e+00  3.684536e+00  2.063648e+00  4.076509e+00   

                  5             6  
count  1.580000e+02  1.580000e+02  
mean   3.653899e-17 -1.124276e-17  
std    1.003180e+00  1.003180e+00  
min   -2.577958e+00 -2.062826e+00  
25%   -6.190260e-01 -6.626358e-01  
50%   -9.474745e-02  1.018854e-01  
75%    4.974609e-01  6.287465e-01  
max    3.661131e+00  3.781323e+00

In [11]:
X = x1[[0,1,2,3,4,5]]
Y = x["crewx100"]

In [12]:
X

0         1         2         3         4         5
0   -1.276402 -1.104984 -1.193956 -1.225331 -1.184588  0.318057
1   -1.276402 -1.104984 -1.193956 -1.225331 -1.184588  0.318057
2    1.358105 -0.647310 -0.372926 -0.509363 -0.314095 -0.940676
3   -0.617775  1.043215  1.169614  0.782736  1.357341 -0.338017
4    0.172577  0.810215  0.825445  0.441533  0.982670 -0.178934
..        ...       ...       ...       ...       ...       ...
153  0.831204 -1.830796 -1.844975 -2.987284 -1.907008  1.244688
154 -0.222599  0.148615  0.118448  0.368817  0.188457 -0.083716
155  1.226380 -1.776662 -1.749603 -2.086730 -1.815023 -0.701471
156  1.489831 -1.776662 -1.740273 -2.086730 -1.815023 -0.912808
157  0.962929 -1.523507 -1.594104 -1.096680 -1.631052  0.925360

[158 rows x 6 columns]

In [13]:
Y

0       3.55
1       3.55
2       6.70
3      19.10
4      10.00
       ...  
153     0.59
154    12.00
155     0.88
156     0.88
157     1.80
Name: crewx100, Length: 158, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0) 

In [15]:
print(len(X_train),len(y_train),len(X_test),len(y_test))

110 110 48 48


In [16]:
X_train

0         1         2         3         4         5
61   0.172577 -0.426651 -0.600990 -0.526143 -0.560885  0.452755
2    1.358105 -0.647310 -0.372926 -0.509363 -0.314095 -0.940676
147 -0.486050 -1.247177 -1.511172 -1.208550 -1.545798  2.848296
43  -1.276402  1.097107  2.025890  0.771549  1.384263 -1.211234
155  1.226380 -1.776662 -1.749603 -2.086730 -1.815023 -0.701471
..        ...       ...       ...       ...       ...       ...
9   -1.276402  1.049655  1.922225  0.771549  1.355097 -1.174076
103 -0.486050  1.012632  0.945697  0.771549  0.935556 -0.050042
67  -1.408127  1.676442  2.190718  1.565826  1.691628 -0.717727
117  0.040852 -1.403463 -1.581665 -1.678404 -1.622078  2.333887
47   3.729162 -0.025805 -0.056747  0.838671  0.150317 -0.073265

[110 rows x 6 columns]

# Linear Reg

In [17]:
from sklearn import linear_model
from sklearn.metrics import r2_score

Linreg = linear_model.LinearRegression()  
Linreg.fit(X_train, y_train)


y_train_pred_Linreg = Linreg.predict(X_train)
y_test_pred_Linreg = Linreg.predict(X_test)


r2_train_Linreg = r2_score(y_train, y_train_pred_Linreg)
r2_test_Linreg = r2_score(y_test, y_test_pred_Linreg)

r2_train_Linreg, r2_test_Linreg

(0.9118485946473178, 0.957979988701403)

In [18]:
from sklearn.linear_model import LinearRegression
Linreg = LinearRegression()  
Linreg.fit(X_train, y_train) ###training the algorithm, note regression is done without normalizing the X, y
### To retrieve the intercept:
print('Intercept (train):', Linreg.intercept_)
### To retrieving the slope:
print('Slopes (train):', Linreg.coef_)

from sklearn.metrics import r2_score
y_pred_Linreg_train = Linreg.predict(X_train)
### Fitting y using the x_train data
r2_score_Linreg_train = r2_score(y_train, y_pred_Linreg_train)

print('R2_score (train): ', r2_score_Linreg_train)

Intercept (train): 7.80653447609923
Slopes (train): [-0.06850255  0.25812795 -1.42695736  0.82914541  3.68927452  0.02995278]
R2_score (train):  0.9118485946473178


In [19]:
from sklearn.metrics import mean_squared_error
### Predicting R2 Score using Test Set but Intercept(train) and Slopes(train) from Training results
y_pred = Linreg.intercept_ + np.dot(X_test,Linreg.coef_.T)
rmse_y_pred = (np.sqrt(mean_squared_error(y_test, y_pred)))
def tss(y_test):
    return ((y_test - np.mean(y_test))**2).sum()
R2_pred=1-(len(y_test)*(rmse_y_pred)**2)/tss(y_test)
print("Pred_RMSE:",rmse_y_pred)
print("R2_pred:",R2_pred)

Pred_RMSE: 0.6504043106009932
R2_pred: 0.957979988701403


# Ridge

In [20]:
from sklearn import linear_model
Ridge=linear_model.Ridge(alpha=0.05)
Ridge.fit(X_train, y_train)

# Predictions on training and test sets
y_train_pred_ridge = Ridge.predict(X_train)
y_test_pred_ridge = Ridge.predict(X_test)

r2_train_ridge = r2_score(y_train, y_train_pred_ridge)
r2_test_ridge = r2_score(y_test, y_test_pred_ridge)

r2_train_ridge, r2_test_ridge

(0.91183614324737, 0.9581595215538381)

In [21]:
from sklearn import linear_model
Ridge=linear_model.Ridge(alpha=0.05)
Ridge.fit(X_train, y_train) ### training the algorithm, note regression is done without normalizing the X, y
### To retrieve the intercept:
print('Intercept (train):', Ridge.intercept_)
### To retrieving the slope:
print('Slopes (train):', Ridge.coef_)

from sklearn.metrics import r2_score
y_pred_ridge_train = Ridge.predict(X_train)
### Fitting y using the x_train data
r2_score_ridge_train = r2_score(y_train, y_pred_ridge_train)

print('R2_score (train): ', r2_score_ridge_train)

Intercept (train): 7.806583180575316
Slopes (train): [-0.06771503  0.27680153 -1.36935954  0.83123131  3.61075632  0.02745032]
R2_score (train):  0.91183614324737


In [22]:
### Predicting R2 Score using Test Set but Intercept(train) and Slopes(train) from Ridge Training results
y_pred_Ridge = Ridge.intercept_ + np.dot(X_test,Ridge.coef_.T)
rmse_y_pred_Ridge = (np.sqrt(mean_squared_error(y_test, y_pred_Ridge)))
def tss(y_test):
    return ((y_test - np.mean(y_test))**2).sum()
R2_pred_Ridge = 1-(len(y_test)*(rmse_y_pred_Ridge)**2)/tss(y_test)
print("Pred_RMSE_Ridge:",rmse_y_pred_Ridge)
print("R2_pred_Ridge:",R2_pred_Ridge)

Pred_RMSE_Ridge: 0.6490133788743184
R2_pred_Ridge: 0.9581595215538381


In [23]:
predictions = Ridge.predict(X)
predictions=pd.DataFrame(predictions)
predictions

0
0     3.935046
1     3.935046
2     6.462771
3    12.077940
4    10.799120
..         ...
153   0.435268
154   8.685343
155   1.320176
156   1.283759
157   2.727045

[158 rows x 1 columns]

# Lasso

In [24]:
from sklearn import linear_model
Lasso=linear_model.Lasso(alpha=0.01)
Lasso.fit(X_train, y_train) ### training the algorithm, note regression is done without normalizing the X, y
### To retrieve the intercept:
print('Intercept (train):', Lasso.intercept_)
### To retrieving the slope:
print('Slopes (train):', Lasso.coef_)

from sklearn.metrics import r2_score
y_pred_lasso_train = Lasso.predict(X_train)
r2_score_lasso_train = r2_score(y_train, y_pred_lasso_train)

print('R2_score (train): ', r2_score_lasso_train)

y_pred_lasso_test = Lasso.predict(X_test)
r2_score_lasso_test = r2_score(y_test, y_pred_lasso_test)

print("R2_pred_Lasso:",r2_score_lasso_test)

Intercept (train): 7.802439214331301
Slopes (train): [-0.05081069  0.11904811 -0.81767346  0.84627291  3.21345059  0.07302589]
R2_score (train):  0.9109477560568731
R2_pred_Lasso: 0.9567576421666848


In [25]:
# Create a LASSO regression model with alpha = 0.01
lasso_model = linear_model.Lasso(alpha=0.001)

# Train the model
lasso_model.fit(X_train, y_train)

# Predictions on training and test sets
y_train_pred_lasso = lasso_model.predict(X_train)
y_test_pred_lasso = lasso_model.predict(X_test)

# R2 scores for training and test sets using LASSO Regression
r2_train_lasso = r2_score(y_train, y_train_pred_lasso)
r2_test_lasso = r2_score(y_test, y_test_pred_lasso)

r2_train_lasso, r2_test_lasso

(0.9118397457423145, 0.9580194029786796)

In [26]:
from sklearn import linear_model
Lasso=linear_model.Lasso(alpha=0.001)
Lasso.fit(X_train, y_train) ### training the algorithm, note regression is done without normalizing the X, y
### To retrieve the intercept:
print('Intercept (train):', Lasso.intercept_)
### To retrieving the slope:
print('Slopes (train):', Lasso.coef_)

from sklearn.metrics import r2_score
y_pred_lasso_train = Lasso.predict(X_train)
### Fitting y using the x_train data
r2_score_lasso_train = r2_score(y_train, y_pred_lasso_train)

print('R2_score (train): ', r2_score_lasso_train)
### R2_score (train) is the R-square in the linear regression involving only the training data set

Intercept (train): 7.806143863499729
Slopes (train): [-0.06671174  0.24613938 -1.36676981  0.83038858  3.64096427  0.03391695]
R2_score (train):  0.9118397457423145


In [27]:
### Predicting R2 Score using Test Set but Intercept(train) and Slopes(train) from Lasso Training results
y_pred_Lasso = Lasso.intercept_ + np.dot(X_test,Lasso.coef_.T)
rmse_y_pred_Lasso = (np.sqrt(mean_squared_error(y_test, y_pred_Lasso)))
def tss(y_test):
    return ((y_test - np.mean(y_test))**2).sum()
R2_pred_Lasso = 1-(len(y_test)*(rmse_y_pred_Lasso)**2)/tss(y_test)
print("Pred_RMSE_Lasso:",rmse_y_pred_Lasso)
print("R2_pred_Lasso:",R2_pred_Lasso)

Pred_RMSE_Lasso: 0.6500992032336775
R2_pred_Lasso: 0.9580194029786796


In [28]:
#define new observation
new = [-0.617775,1.043215,1.169614,0.782736,1.357341,-0.338017]

#predict hp value using lasso regression model
Lasso.predict([new])

array([12.08608052])

In [60]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
new = [6,30.277,6.94,	5.94,	3.55,	42.64,3.55]
x.loc[-1] = new
x
x1=scaler.fit_transform(x)
x1 = pd.DataFrame(x1)
x1

0         1         2         3         4         5         6
0   -1.265913 -1.097299 -1.184896 -1.215745 -1.175681  0.316954 -1.205852
1   -1.265913 -1.097299 -1.184896 -1.215745 -1.175681  0.316954 -1.205852
2    1.363482 -0.639931 -0.364939 -0.500882 -0.306266 -0.945355 -0.305212
3   -0.608564  1.049461  1.175585  0.789223  1.363101 -0.340984  3.240164
4    0.180254  0.816617  0.831866  0.448546  0.988894 -0.181448  0.638315
..        ...       ...       ...       ...       ...       ...       ...
154 -0.214155  0.155460  0.125792  0.375942  0.195665 -0.085960  1.210150
155  1.232012 -1.768527 -1.739816 -2.075814 -1.805335 -0.705469 -1.969252
156  1.494951 -1.768527 -1.730498 -2.075814 -1.805335 -0.917407 -1.969252
157  0.969072 -1.515541 -1.584521 -1.087293 -1.621592  0.925983 -1.706208
158 -1.265913 -1.097299 -1.184896 -1.215745 -1.175681  0.316954 -1.205852

[159 rows x 7 columns]

In [29]:
predictions = Lasso.predict(X)
predictions=pd.DataFrame(predictions)
predictions

0
0     3.931421
1     3.931421
2     6.467434
3    12.086079
4    10.804304
..         ...
153   0.439980
154   8.685271
155   1.313306
156   1.275811
157   2.727795

[158 rows x 1 columns]

In [30]:
from sklearn.linear_model import LassoCV

#define model
model = LassoCV(cv=4, random_state=0)

#fit model
model.fit(X_train, y_train)

#display lambda that produced the lowest test MSE
print(model.alpha_)

0.00459121852597049


# Cross Validation

In [31]:
from sklearn.model_selection import cross_val_score
scoresLinreg = cross_val_score(estimator = Linreg, X = X_train, y = y_train, cv = 4)
### This combined training set X_train, y_train is split into k=5 (cv=5) folds for each of k=1,2,...,5 repetitions
print(scoresLinreg)
### Score is R2 measure, there are 5 scores since k=cv=5, one for each repetition 
print("%0.4f mean R2 with a standard deviation of %0.4f" % (scoresLinreg.mean(), scoresLinreg.std()))

[0.87938812 0.83344863 0.94233134 0.97065224]
0.9065 mean R2 with a standard deviation of 0.0536


In [32]:
from sklearn import linear_model
Ridge=linear_model.Ridge(alpha=0.05,)
### Do not need to specify Ridge.fit(X_train, y_train) 
### Above steps may be repeated in order to try different hyperparameter of alpha and select one with highest ave R2

from sklearn.model_selection import cross_val_score
scoresRidge = cross_val_score(estimator = Ridge, X = X_train, y = y_train, cv = 4)
### This combined training set X_train, y_train is split into k=5 (cv=5) folds for each of k=1,2,...,5 repetitions
print(scoresRidge)
### Score is R2 measure, there are 5 scores since k=cv=5, one for each repetition 
print("%0.4f mean R2 with a standard deviation of %0.4f" % (scoresRidge.mean(), scoresRidge.std()))

[0.8804058  0.83267197 0.94295746 0.97064257]
0.9067 mean R2 with a standard deviation of 0.0538


In [62]:
from sklearn import linear_model
Lasso=linear_model.Lasso(alpha=0.01,)

from sklearn.model_selection import cross_val_score
scoresLasso = cross_val_score(estimator = Lasso, X = X_train, y = y_train, cv = 4)
print(scoresLasso)
### Score is R2 measure, there are 4 scores since k=cv=4, one for each repetition 
print("%0.5f mean R2 with a standard deviation of %0.5f" % (scoresLasso.mean(), scoresLasso.std()))

[0.88414514 0.82990918 0.94387686 0.96812388]
0.90651 mean R2 with a standard deviation of 0.05376
